### ISSUE TITLE
The procedure to create a channel from scratch fails

### ISSUE THREAD

**Issue by denisri** [neurospin/neuro-forge#3]
using the instructions from the main README.md:
```
pixi run neuro-forge init channel
```
fails after a few minutes of building, while building mesalib:
```
 │ │ +++ /volatile/home/dr144257/casa_distro/condadev/neuro-forge/channel/bld/rattler-build_mesalib-devel-only
 │ │ _1711636770/work/conda/bin/conda shell.posix activate
 │ │ Traceback (most recent call last):
 │ │   File "/volatile/home/dr144257/casa_distro/condadev/neuro-forge/channel/bld/rattler-build_mesalib-devel-
 │ │ only_1711636770/work/conda/bin/conda", line 12, in <module>
 │ │     from conda.cli import main
 │ │ ModuleNotFoundError: No module named 'conda.cli'
 │ │ ++ ask_conda=
 │ │ ++ return
 │ │
 │ ╰─────────────────── (took 22 seconds)
 │
 ╰─────────────────── (took 23 seconds)
 × error Error building package: Script failed with status ExitStatus(unix_wait_status(256))
Error:   × Script failed with status ExitStatus(unix_wait_status(256))

Traceback (most recent call last):
  File "/volatile/home/dr144257/casa_distro/condadev/neuro-forge/neuro-forge", line 50, in <module>
    fire.Fire(Commands)
  File "/volatile/home/dr144257/casa_distro/condadev/neuro-forge/.pixi/envs/default/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volatile/home/dr144257/casa_distro/condadev/neuro-forge/.pixi/envs/default/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/volatile/home/dr144257/casa_distro/condadev/neuro-forge/.pixi/envs/default/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/volatile/home/dr144257/casa_distro/condadev/neuro-forge/neuro-forge", line 39, in init
    check_call(command)
  File "/volatile/home/dr144257/casa_distro/condadev/neuro-forge/.pixi/envs/default/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rattler-build', 'build', '-r', '/volatile/home/dr144257/casa_distro/condadev/neuro-forge/recipes/mesalib-devel-only', '--output-dir', 'channel']' returned non-zero exit status 1.
```
it seems that there is a missing dependency: python module `conda.cli` is not present.

**Comment by denisri** [comment]
It rather seems that it is a path problem: conda.cli is actually installed in the pixi environment (in python 3.12) but is not found from the conda executable. Maybe the wrong python gets run, or the python path is not set as it should.

**Comment by sapetnioc** [comment]
I will test the procedures from a container because I may find some missing dependencies on the host. This is probably why it worked for me.

**Comment by sapetnioc** [comment]
I was not able to reproduce the problem. I am using a mamba environment inside the build script. I suspect that the activation of this environment may have side effect after the build script (but that was not the case for me), therfore I added a deactivation at the end.

I had been able to run the procedure from within a container with only pixi and git. I had to make some changes because of the cache of pixi and rattler-build (HOME was read-only). There is a variable to set pixi cache location but I did not find one yet for rattler-build (I change HOME before calling it).

**Comment by denisri** [comment]
Still no luck for me... after updating it behaves the same.

**Comment by sapetnioc** [comment]
Crap, I'd like to be able to reproduce. If it is on your laptop, I'd like to take a look tomorrow.

**Comment by denisri** [comment]
yes, sure !
